### ISSUE TITLE
Contact deletion not working

### ISSUE THREAD

**Issue by akozin** [tristanhimmelman/THContactPicker#56] opened 2016-02-21 13:41 UTC
Hello, in new version 2.0 `EXC_BAD_ACCESS` error occurs, when i trying to delete contact from THContactTextField.
I had to press backspace button twice for deleting. After a first press a contact was selected and after a second an error was occurred. 
The error occurs in this block of code:

```
dispatch_async(dispatch_get_main_queue(), ^{
    [self.delegate textFieldDidHitBackspaceWithEmptyText:self];
});
```

After deleting dispatch_async everything is working fine:
`[self.delegate textFieldDidHitBackspaceWithEmptyText:self];`

I attached a zipped 
[THContactPicker_deleteBackward_error_720p.zip](https://github.com/tristanhimmelman/THContactPicker/files/139615/THContactPicker_deleteBackward_error_720p.zip)
video.

**Comment by jguffey** [comment] 2016-03-08 00:47
Hey @akozin is this still happening? I can't reproduce on 9.2 nor 8.4. 

Thanks

**Comment by brandonshin** [comment] 2016-03-10 03:19
Able to reproduce consistently on 9.2 when deleting multiple contacts in succession. See an EXC_BADACCESS on line 315 of `THContactPickerView` on removal of the second contact.

`[self.delegate contactPicker:self didRemoveContact:[contact nonretainedObjectValue]];`

Happens when calling `[contact nonretainedObjectValue]`, removing the mainThread dispatcher doesn't seem to have any effect

**Comment by brandonshin** [comment] 2016-03-10 03:57
@jguffey Able to reproduce consistently on 9.2 when deleting multiple contacts in succession. See an `EXC_BADACCESS` on line 315 of `THContactPickerView` on removal of the second contact.

`[self.delegate contactPicker:self didRemoveContact:[contact nonretainedObjectValue]];`

Happens when calling `[contact nonretainedObjectValue]`, removing the mainThread dispatcher doesn't seem to have any effect

**Comment by tomoyuki28jp** [comment] 2016-03-25 11:21
I'm having a similar issue. When I add two contacts and then remove the last one, EXC_BAD_ACCESS occurs in `[self.delegate contactPickerDidRemoveContact:[contact nonretainedObjectValue]]`.

**Comment by spencer-microsoft** [comment] 2016-06-23 21:22
I'm inconsistently having the same issue as @tomoyuki28jp on iOS 9.3. I selected 3 contacts and deleted them all, and it crashed at that breakpoint after deleting the third.

**Comment by spencer-microsoft** [comment] 2016-08-11 20:54
@akozin @brandonshin @tomoyuki28jp I figured out the issue. It's because you're not holding a strong reference to the contact. The picker view doesn't hold a strong reference to the contact, so it gets recycled.

@jguffey I think this issue can be closed

**Comment by jguffey** [comment] 2016-09-01 17:31
@spencer-microsoft Awesome, glad you resolved the issue.

@tristanhimmelman please close this issue.

**Closed as completed** 2016-09-01 17:47 UTC

**Comment by itsliyang** [comment] 2016-10-14 00:55
Is this issue fixed? I still have this issue when I tried to delete contact and I got bad access at line [self.delegate contactPicker:self didRemoveContact:[contact nonretainedObjectValue]];

**Comment by spencer-microsoft** [comment] 2016-10-24 22:46
@lywan you have to keep a strong reference to your contacts. The reason you get that crash is because you didn't keep a pointer to it, and then you tried to access it after it no longer existed.

**Comment by sergstav** [comment] 2018-08-22 12:56
@spencer-microsoft, @tristanhimmelman  hello, can you add more details, I get this crash, even when I dont do any actions with contacts, just implement empty delegate methods, and its crashed.
